nvitop/cli.py, nvitop/gui/__init__.py, nvitop/gui/library/__init__.py, nvitop/gui/library/libcurses.py
- Bug fix
- Operating system and version: CentOS Linux release 7.9.2009 (Core)
- Terminal emulator and version: Windows Terminal 1.12.10732.0
- Python version: `3.6.8`
- NVML version (driver version): `512.15`
- `nvitop` version or commit: `dev@93926f3`
The fresh installed CentOS 7 does not have locale `C.UTF-8`.
```console
[root@centos /]# locale -a
C
en_US.utf8
POSIX
[root@centos /]# locale
LANG=en_US.UTF-8
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=en_US.UTF-8 …
```
=> Fix locale encoding when `C.UTF-8` is not available

README.md, docs/source/apis/index.rst, nvitop/cli.py, nvitop/core/libnvml.py, nvitop/version.py, requirements.txt, setup.cfg, setup.py
- NVML version (driver version): [e.g. `470.129.06`]
- `nvitop` version or commit: [e.g. `dev@2906d4f0`]
Unpin the package `nvidia-ml-py` version. By default, `pip` will install dependency `nvidia-ml-py >= 11.450.51, < 11.510.69`, or skip if already installed. To specify the `nvidia-ml-py` version with `nvitop`. Use:
```bash
pip3 install 'nvitop[pynvml-11.450.51]'
```
or
```bash
pip3 install nvitop nvidia-ml-py==11.495.46
```
An extra alias is added for CUDA 10.x drivers as:
```bash
pip3 install 'nvitop[cuda10]'  # installs nvidia-ml-py==11.450.51
```
The users …
=> Add extra options to specify `nvidia-ml-py` version

docs/source/apis/core/libnvml.rst, nvitop/callbacks/keras.py, nvitop/callbacks/pytorch_lightning.py, nvitop/cli.py, nvitop/core/__init__.py, nvitop/core/device.py, nvitop/core/host.py, nvitop/core/libnvml.py, nvitop/core/process.py, nvitop/gui/library/device.py, nvitop/version.py
- Refactor
- `nvitop` version or commit: `main@6bf151`
Use a module-based approach rather than a singleton class. Previously, we use a singleton class `libnvml` and the singleton `nvml` to support the context manager (`with` statement). Now, the mechanism is replaced by a custom module type.
Simplify module hierarchy. Make the IDE happy and let sphinx generate more documents from `autoapi`.
=> refactor(core/libnvml): use module-based approach rather than singleton

docs/source/apis/core/libcuda.rst, docs/source/apis/index.rst, nvitop/core/__init__.py, nvitop/core/device.py, nvitop/core/libcuda.py, nvitop/gui/screens/main/process.py
- `nvitop` version or commit: `main@0a9048`
Add Python bindings for CUDA driver APIs.
This would simplify the `CUDA_VISIBLE_DEVICES` environment variable parsing. Handles non-standard `CUDA_VISIBLE_DEVICES` format. For example:
```console
$ nvidia-smi -L
GPU 0: NVIDIA GeForce RTX 3070 (UUID: GPU-4ba9dbe6-7cbf-4621-a31b-aa2ca6247e31)
$ CUDA_VISIBLE_DEVICES='GPU-4ba9dbe6' ipython
Python 3.9.13 (main, May 17 2022, 14:19:07) 
Type 'copyright', 'credits' or 'license' for more information
IPython 8.4.0 -- An enhanced …
```
=> feat(core/libcuda): add Python bindings for CUDA driver APIs

README.md, nvitop/cli.py, nvitop/gui/library/history.py, nvitop/gui/library/libcurses.py, nvitop/gui/screens/main/device.py, nvitop/gui/screens/main/host.py, nvitop/gui/screens/main/process.py
- `nvitop` version or commit: `v0.7.1`
Use gradient colors for spectrum-like bar charts. This requires the user to set `TERM` to `*-256color` (e.g. `xterm-256color` or `tmux-256color`).
Make `nvitop` more colorful.
N/A
=> feat(gui): add 256 color support for bar charts

README.md, docs/source/index.rst, nvitop/core/process.py, nvitop/gui/library/__init__.py, nvitop/gui/library/history.py, nvitop/gui/library/libcurses.py, nvitop/gui/library/process.py, nvitop/gui/library/selection.py, nvitop/gui/library/utils.py, nvitop/gui/screens/__init__.py, nvitop/gui/screens/environ.py, nvitop/gui/screens/help.py, nvitop/gui/screens/main/__init__.py, nvitop/gui/screens/main/host.py, nvitop/gui/screens/main/process.py, nvitop/gui/screens/metrics.py, nvitop/gui/screens/treeview.py, nvitop/gui/top.py
- `nvitop` version or commit: `main`
Add process metrics screen. Watch metrics for a specific process in the terminal.
In addition to metrics (`GPU-MEM`, `%SM`, `%CPU`, `%MEM`, `TIME`) already on the main screen, it adds:
- live graph for `%CPU` and metric for max `%CPU`
- live graph for `HOST-MEM` and `%MEM`, and metric for max `HOST-MEM`
- live graph for `GPU-MEM` and `%GPU-MEM`, and metric for max `GPU-MEM`
- live graph for `%SM` and metric for max `%SM`
- metric `%GMBW`: GPU memory bandwidth utilization
- metric …
=> feat(gui/metrics): add process metrics screen

.github/ISSUE_TEMPLATE.md, README.md, nvitop/cli.py, nvitop/core/libnvml.py, nvitop/version.py, pyproject.toml, requirements.txt
- `nvitop` version or commit: `v0.7.1`
Automatically patch the `pynvml` module when the first call fails when calling the versioned APIs. Now we support a more broad range of the [PyPI package `nvidia-ml-py`](https://pypi.org/project/nvidia-ml-py/) dependency versions.
See #29 for more details.
Resolves #29
Closes #13
Using `nvidia-ml-py == 11.515.48` with the NVIDIA R430 driver (CUDA 10.x):
```console
$ pip3 install --ignore-installed .
Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
Processing …
```
=> feat(core/libnvml): add compatibility layers for NVML Python bindings

README.md, docs/source/core/collector.rst, nvitop/core/__init__.py, nvitop/core/collector.py
- `nvitop` version or commit: `v0.10.1`
- `python-ml-py` version: `11.515.75`
Add a function to create a background daemon for metrics collectors.
A minimal example:
```python
from nvitop import collect_in_background
def on_collect(metrics):
print(metrics)
return True
collect_in_background(on_collect)  # print metrics to stdout every 1 second
```
Resolves #47
=> feat(core/collector): add function and method to collect metrics in background thread

.github/workflows/build.yaml, Dockerfile, README.md
- Bug fix
- Python version: `3.10.8`
- NVML version (driver version): `525.60.11`
- `nvitop` version or commit: `main@c04fbb`
- `python-ml-py` version: `11.515.75`
- Migrate the docker image repo to [nvcr.io/nvidia/driver](https://catalog.ngc.nvidia.com/orgs/nvidia/containers/driver). The old repo on [Docker Hub](https://hub.docker.com/r/nvidia/driver) is out of maintenance.
- Add minimal test for the `Dockerfile` in GitHub Actions.
Python 3.6 is end-of-life and the highest supported `setuptools` does not support `pyprocject.toml` based projects. It cannot install the dependencies correctly. This PR replaces the …
=> fix(Dockerfile): migrate docker image repo to nvcr.io/nvidia/driver

README.md, docs/source/core/libcudart.rst, docs/source/index.rst, docs/source/spelling_wordlist.txt, nvitop/__init__.py, nvitop/core/__init__.py, nvitop/core/device.py, nvitop/core/libcuda.py, nvitop/core/libcudart.py
- Python version: `3.11.1`
- NVML version (driver version): `525.60.11`
- `nvitop` version or commit: `0.11.0`
- `python-ml-py` version: `11.515.75`
Add Python bindings for CUDA Runtime APIs (`cudart`) and add method `cuda_runtime_version()`.
Support to detect the CUDA runtime version.
```python
In [1]: from nvitop import *
In [2]: Device.driver_version()
Out[2]: '525.60.11'
In [3]: Device.cuda_driver_version()
Out[3]: '12.0'
In [4]: Device.max_cuda_version()
Out[4]: '12.0'
In [5]: Device.cuda_runtime_version()
Out[5]: '11.8'
```
```console
$ LD_LIBRARY_PATH="/usr/local/cuda-10.2/lib64:${LD_LIBRARY_PATH}" python3 -c 'from …
```
=> feat(core/libcudart): add Python bindings for CUDA Runtime APIs

.github/workflows/lint.yaml, CHANGELOG.md, nvitop/api/device.py, nvitop/api/host.py, nvitop/api/process.py, nvitop/gui/library/device.py
- Breaking changes
Move `TTLCache` usage to CLI-only. Public APIs in `nvitop.api` will always return immediate results.
In the previous implementation, the public APIs may return cached results. Now all caching mechanisms are moved to CLI-only. This is more consistent with other packages such as `psutil.Process`.
=> refactor(api): move `TTLCache` usage to CLI-only

CHANGELOG.md, nvitop/api/device.py
- Bug fix
Further isolate the `CUDA_VISIBLE_DEVICE` parser in a subprocess. We are using both `subprocess` and `mutliprocessing` modules.
Fixes #69
```python
from nvitop import CudaDevice
print(CudaDevice.count())
```
Before:
```console
$ python3 test.py
Traceback (most recent call last):
File "<string>", line 1, in <module>
File "/home/linuxbrew/.linuxbrew/opt/python@3.11/lib/python3.11/multiprocessing/spawn.py", line 120, in spawn_main
exitcode = _main(fd, parent_sentinel)
^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/home/linuxbrew/.linuxbrew/opt/python@3.11/lib/python3.11/multiprocessing/spawn.py", line 129, in _main
prepare(preparation_data)
File "/home/linuxbrew/.linuxbrew/opt/python@3.11/lib/python3.11/multiprocessing/spawn.py", line 240, in prepare …
```
=> fix(api/device): further isolate the `CUDA_VISIBLE_DEVICE` parser in a subprocess

.pre-commit-config.yaml, docs/source/spelling_wordlist.txt, nvitop/api/device.py, nvitop/api/libnvml.py, nvitop/api/process.py, nvitop/api/utils.py, nvitop/cli.py, nvitop/version.py, pyproject.toml, requirements.txt
- Bug fix
The start with the NVIDIA R510 driver, the new version 3 APIs have been added for `nvmlDeviceGet{Compute,Graphics,MPSCompute}RunningProcesses`. But the version 3 functions still use the version 2 type struct as the function argument type:
```python
class c_nvmlProcessInfo_v2_t(pynvml._PrintableStructure):
_fields_ = [
('pid', ctypes.c_uint),
('usedGpuMemory', ctypes.c_ulonglong),
('gpuInstanceId', ctypes.c_uint),
('computeInstanceId', ctypes.c_uint),
]
_fmt_ = {
'usedGpuMemory': '%d B',
}
```
Recently, the NVIDIA R535 driver came out. The version 3 APIs starts to use the new version 3 type struct without a version bump. This results in invalid memory access and produces the wrong results.
```python
class c_nvmlProcessInfo_v3_t(pynvml._PrintableStructure):
_fields_ = [
('pid', …
```
=> fix(api/libnvml): fix process info support for NVIDIA R535 driver (CUDA 12.2+)

CHANGELOG.md, nvitop/api/device.py, nvitop/api/process.py
- Bug fix
Remove the extra 2s timestamp margin for GPU process utilization. Such a margin may cause the API returns the average utilization rather than the instant values.
Resolves #83
=> fix(api/device): use recent timestamp for GPU process utilization query

CHANGELOG.md, nvitop/api/libnvml.py
- Bug fix
Add an extra handler to check the removal of the process info v3 APIs.
Copied from https://github.com/XuehaiPan/nvitop/issues/88#issuecomment-1680052592:
Version change:
495.46 -> 510.39.01: https://github.com/NVIDIA/nvidia-settings/commit/b2f0e7f437c42d92ed58120ec8d880f5f4b90d60
- Add process info v3 APIs but use v2 `nvmlProcessInfo_st` struct type
- default: 
- `nvmlDeviceGetComputeRunningProcesses` -> `nvmlDeviceGetComputeRunningProcesses_v3`
- `nvmlProcessInfo_st` -> `nvmlProcessInfo_v2_st`
530.41.03 -> 535.43.02: https://github.com/NVIDIA/nvidia-settings/commit/39c3e28e84f3ffb034abaf1ae92dbb570c207d05
- Process info v3 APIs use v3 `nvmlProcessInfo_st` struct type without a version bump
- default: 
- `nvmlDeviceGetComputeRunningProcesses` -> …
=> fix(api/libnvml): fix removal for process info v3 APIs on the upstream 535.98 driver

.pre-commit-config.yaml, CHANGELOG.md, nvitop/api/device.py, nvitop/api/libnvml.py, nvitop/api/process.py
- Bug fix
Handle the upstream re-addition for the process info v3 APIs with the v2 struct type.
See also #88 and #89:
- #88
- #89
=> fix(api/libnvml): fix upstream changes for process info v3 APIs on 535.104.05 driver

.pre-commit-config.yaml, CHANGELOG.md, nvitop/api/device.py, nvitop/api/libcuda.py, nvitop/api/utils.py, nvitop/select.py, pyproject.toml
- Bug fix
Change string buffer to a byte array for argument passing.
Fixes #99
=> fix(libcuda): fix `cuDeviceGetUuid()` when the UUID contains `0x00`

.pre-commit-config.yaml, CHANGELOG.md, nvitop-exporter/nvitop_exporter/exporter.py, nvitop/api/device.py, nvitop/cli.py, nvitop/select.py
Remove gauge entries for gone processes.
Resolves #106
=> feat(exporter): remove metrics if process is gone

.pre-commit-config.yaml, CHANGELOG.md, README.md, docs/requirements.txt, docs/source/callbacks.rst, docs/source/spelling_wordlist.txt, nvitop/callbacks/keras.py, nvitop/callbacks/lightning.py, nvitop/callbacks/pytorch_lightning.py
- Bug fix
Populate the implementation for `GpuStatsLogger` callback to `nvitop.lightning` based on `lightning.pytorch..callbacks.Callback`.
Fixes #112
Closes #113
=> fix(callbacks/lightning): populate callback for `lightning`

.pre-commit-config.yaml, CHANGELOG.md, docs/source/spelling_wordlist.txt, nvitop/api/host.py, nvitop/gui/library/utils.py, nvitop/select.py
Move the `getuser()` function under a `contextlib.suppress(ImportError, OSError)` context.
Resolves #129
- #129
cc @landgraf @quarckster
This would also resolve an incoming change of the exception type in the Python upstream in Python 3.13.
- python/cpython#29739
=> feat(api): handle exceptions for function `getpass.getuser()`

CHANGELOG.md, nvitop/api/collector.py
The docstrings of `ResourceMetricCollector` referred to the `clear()` function as `reset()`, which is not existing. 
Therefore, I replaced each mention of `reset()` with `clear()` in the documentation.
- Operating system and version: [e.g. Ubuntu 20.04 LTS / Windows 10 Build 19043.1110]
- Terminal emulator and version: [e.g. GNOME Terminal 3.36.2 / Windows Terminal 1.8.1521.0]
- Python version: [e.g. `3.7.2` / `3.9.6`]
- NVML version (driver version): [e.g. `460.84`]
- `nvitop` version or commit: [e.g. `0.10.0` / `0.10.1.dev7+ga083321` / `main@75ae3c`]
- `python-ml-py` version: [e.g. `11.450.51`]
- Locale: [e.g. `C` / `C.UTF-8` / `en_US.UTF-8`]
Within the `ResourceMetricCollector` class, the `clear()` function was not used in the documentation for the …
=> fix(collector): fix documentation for `ResourceMetricCollector.clear()` function

.editorconfig, .pre-commit-config.yaml, README.md, nvitop-exporter/README.md, nvitop-exporter/dashboard.json, nvitop-exporter/nvitop_exporter/exporter.py
Add an example JSON model for grafana dashboard.
Resolves #122
=> feat(exporter): add dashboard example

.github/ISSUE_TEMPLATE/bug-report.yaml, .github/ISSUE_TEMPLATE/feature-request.yaml, .github/ISSUE_TEMPLATE/questions.yaml, .pre-commit-config.yaml, CHANGELOG.md, nvitop-exporter/nvitop_exporter/exporter.py, nvitop/api/device.py
- Bug fix
Add guard `self.handle is not None` in query functions.
Fixes #145
Fixes #139
=> fix(api/device): fix passing invalid device handle to NVML functions

CHANGELOG.md, README.md, docs/source/spelling_wordlist.txt, nvitop-exporter/nvitop_exporter/cli.py, nvitop/__init__.py, nvitop/api/__init__.py, nvitop/api/caching.py, nvitop/api/libnvml.py, nvitop/api/termcolor.py, nvitop/api/utils.py, nvitop/cli.py, pyproject.toml, requirements.txt
Vendor third-party dependency `termcolor` from https://github.com/termcolor/termcolor
Remove more third-party dependency.
=> deps(termcolor): vendor third-party dependency `termcolor`

.github/PULL_REQUEST_TEMPLATE.md, .github/workflows/build.yaml, .github/workflows/lint.yaml, .pre-commit-config.yaml, CHANGELOG.md, README.md, docs/source/index.rst, nvitop-exporter/pyproject.toml, nvitop/api/caching.py, nvitop/api/collector.py, nvitop/api/device.py, nvitop/api/libcuda.py, nvitop/api/libcudart.py, nvitop/api/libnvml.py, nvitop/api/process.py, nvitop/api/termcolor.py, nvitop/api/utils.py, pyproject.toml
=> deps(python): drop Python 3.7 support

CHANGELOG.md, README.md, docs/source/callbacks.rst, nvitop/callbacks/__init__.py, nvitop/callbacks/keras.py, nvitop/callbacks/lightning.py, nvitop/callbacks/pytorch_lightning.py, nvitop/callbacks/tensorboard.py
- Breaking changes
Deprecate `nvitop.callbacks` as officially unmaintained due to upstream dependencies.
=> chore(callbacks): deprecate `nvitop.callbacks` as officially unmaintained

CHANGELOG.md, nvitop/api/process.py
- Bug fix
Do not reassign the cache to a new `dict` if it is empty.
Fixes #171
=> fix(api/process): fix snapshot cache for GPU processes with shared host process
